---
files:
  -
    source: "/curbside-pickup/public/metadata/messages/pt-BR.json"
    translation: "/curbside-pickup/public/metadata/messages/%locale%.json"
    type: "json"
  -
    source: "/curbside-pickup/public/metadata/licenses/pt-BR.md"
    translation: "/curbside-pickup/public/metadata/licenses/%locale%.md"
    type: "md"
    